# Generated by Django 5.0.7 on 2024-08-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('atividade', models.CharField(max_length=200)),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('duracao', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['data'],
            },
        ),
    ]
